# Generated by Django 3.2.9 on 2022-01-11 19:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_image',
            field=models.ImageField(default='posts/default.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
