# Generated by Django 3.2.9 on 2021-12-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('id_beneficios', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codigo_compra', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('total', models.FloatField(max_length=10)),
                ('data', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(max_length=16)),
                ('desconto', models.FloatField(max_length=10)),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.cliente')),
            ],
            options={
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('razao_social', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('funcional', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('salario', models.FloatField(max_length=10)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('tipo_func', models.CharField(max_length=50)),
                ('crf', models.CharField(blank=True, max_length=6, null=True, unique=True)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo_barras', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=15)),
                ('preco', models.FloatField(max_length=10)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='ProgramaBeneficios',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('fator_desconto', models.PositiveIntegerField(max_length=2)),
            ],
            options={
                'db_table': 'programa_beneficios',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('preco', models.FloatField(max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('data_hora_entrada', models.DateField(primary_key=True, serialize=False)),
                ('data_hora_saida', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('funcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario')),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoProduto',
            fields=[
                ('numero_pedido', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('data_de_validade', models.DateField()),
                ('data_solicitacao', models.DateField()),
                ('valor_total', models.FloatField(max_length=10)),
                ('cnpj_forn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.fornecedor')),
                ('codigo_barras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.produto')),
                ('num_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario')),
            ],
            options={
                'db_table': 'solicitacao_produto',
            },
        ),
        migrations.CreateModel(
            name='ServicoRealizado',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.cliente')),
                ('id_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.servico')),
                ('num_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario')),
            ],
            options={
                'db_table': 'servico_realizado',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioTelefones',
            fields=[
                ('telefone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('funcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario')),
            ],
            options={
                'db_table': 'funcionario_telefones',
            },
        ),
        migrations.CreateModel(
            name='FornecedorTelefones',
            fields=[
                ('telefone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('cnpj_forn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.fornecedor')),
            ],
            options={
                'db_table': 'fornecedor_telefones',
            },
        ),
        migrations.CreateModel(
            name='CompraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('codigo_barras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.produto')),
                ('codigo_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.compra')),
            ],
            options={
                'db_table': 'compra_produto',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='num_func',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario'),
        ),
        migrations.CreateModel(
            name='ClienteTelefones',
            fields=[
                ('telefone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.cliente')),
            ],
            options={
                'db_table': 'cliente_telefones',
            },
        ),
    ]
