# Generated by Django 3.2.9 on 2021-11-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=30)),
                ('endereco', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('id_beneficios', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
