# Generated by Django 3.2.9 on 2022-01-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraproduto',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientetelefones',
            name='cpf',
            field=models.ForeignKey(db_column='cpf', on_delete=django.db.models.deletion.CASCADE, to='drugstore.cliente'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cpf_cliente',
            field=models.ForeignKey(db_column='cpf_cliente', on_delete=django.db.models.deletion.CASCADE, to='drugstore.cliente'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='num_func',
            field=models.ForeignKey(db_column='num_func', on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario'),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='codigo_barras',
            field=models.ForeignKey(db_column='codigo_barras', on_delete=django.db.models.deletion.CASCADE, to='drugstore.produto'),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='codigo_compra',
            field=models.ForeignKey(db_column='codigo_compra', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='drugstore.compra'),
        ),
        migrations.AlterField(
            model_name='fornecedortelefones',
            name='cnpj_forn',
            field=models.ForeignKey(db_column='cnpj_forn', on_delete=django.db.models.deletion.CASCADE, to='drugstore.fornecedor'),
        ),
        migrations.AlterField(
            model_name='funcionariotelefones',
            name='funcional',
            field=models.ForeignKey(db_column='funcional', on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario'),
        ),
        migrations.AlterField(
            model_name='servicorealizado',
            name='cpf_cliente',
            field=models.ForeignKey(db_column='cpf_cliente', on_delete=django.db.models.deletion.CASCADE, to='drugstore.cliente'),
        ),
        migrations.AlterField(
            model_name='servicorealizado',
            name='id_servico',
            field=models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.CASCADE, to='drugstore.servico'),
        ),
        migrations.AlterField(
            model_name='servicorealizado',
            name='num_func',
            field=models.ForeignKey(db_column='num_func', on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='cnpj_forn',
            field=models.ForeignKey(db_column='cnpj_forn', on_delete=django.db.models.deletion.CASCADE, to='drugstore.fornecedor'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='codigo_barras',
            field=models.ForeignKey(db_column='codigo_barras', on_delete=django.db.models.deletion.CASCADE, to='drugstore.produto'),
        ),
        migrations.AlterField(
            model_name='solicitacaoproduto',
            name='num_func',
            field=models.ForeignKey(db_column='num_func', on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='funcional',
            field=models.ForeignKey(db_column='funcional', on_delete=django.db.models.deletion.CASCADE, to='drugstore.funcionario'),
        ),
    ]
