# Generated by Django 3.2.9 on 2021-11-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0002_auto_20211128_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='CRF',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='crf',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientetelefones',
            name='cpf',
            field=models.ForeignKey(db_column='cpf', on_delete=django.db.models.deletion.CASCADE, to='drugstore.cliente'),
        ),
        migrations.AlterField(
            model_name='programabeneficios',
            name='fator_desconto',
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
